package com.jjas.labpomodoro.domain.model

import com.jjas.labpomodoro.domain.model.ElementCategory.ACTINIDE
import com.jjas.labpomodoro.domain.model.ElementCategory.ALKALINE_EARTH_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.ALKALI_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.HALOGEN
import com.jjas.labpomodoro.domain.model.ElementCategory.LANTHANIDE
import com.jjas.labpomodoro.domain.model.ElementCategory.METALLOID
import com.jjas.labpomodoro.domain.model.ElementCategory.NOBLE_GAS
import com.jjas.labpomodoro.domain.model.ElementCategory.NONMETAL
import com.jjas.labpomodoro.domain.model.ElementCategory.POST_TRANSITION_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.TRANSITION_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.UNKNOWN

/** Los 118 elementos, ordenados por número atómico (índice = número atómico − 1). */
object PeriodicTable {

    const val SIZE = 118

    val elements: List<Element> = listOf(
        e(1, "H", 1, NONMETAL),
        e(2, "He", 18, NOBLE_GAS),
        e(3, "Li", 1, ALKALI_METAL),
        e(4, "Be", 2, ALKALINE_EARTH_METAL),
        e(5, "B", 13, METALLOID),
        e(6, "C", 14, NONMETAL),
        e(7, "N", 15, NONMETAL),
        e(8, "O", 16, NONMETAL),
        e(9, "F", 17, HALOGEN),
        e(10, "Ne", 18, NOBLE_GAS),
        e(11, "Na", 1, ALKALI_METAL),
        e(12, "Mg", 2, ALKALINE_EARTH_METAL),
        e(13, "Al", 13, POST_TRANSITION_METAL),
        e(14, "Si", 14, METALLOID),
        e(15, "P", 15, NONMETAL),
        e(16, "S", 16, NONMETAL),
        e(17, "Cl", 17, HALOGEN),
        e(18, "Ar", 18, NOBLE_GAS),
        e(19, "K", 1, ALKALI_METAL),
        e(20, "Ca", 2, ALKALINE_EARTH_METAL),
        e(21, "Sc", 3, TRANSITION_METAL),
        e(22, "Ti", 4, TRANSITION_METAL),
        e(23, "V", 5, TRANSITION_METAL),
        e(24, "Cr", 6, TRANSITION_METAL),
        e(25, "Mn", 7, TRANSITION_METAL),
        e(26, "Fe", 8, TRANSITION_METAL),
        e(27, "Co", 9, TRANSITION_METAL),
        e(28, "Ni", 10, TRANSITION_METAL),
        e(29, "Cu", 11, TRANSITION_METAL),
        e(30, "Zn", 12, TRANSITION_METAL),
        e(31, "Ga", 13, POST_TRANSITION_METAL),
        e(32, "Ge", 14, METALLOID),
        e(33, "As", 15, METALLOID),
        e(34, "Se", 16, NONMETAL),
        e(35, "Br", 17, HALOGEN),
        e(36, "Kr", 18, NOBLE_GAS),
        e(37, "Rb", 1, ALKALI_METAL),
        e(38, "Sr", 2, ALKALINE_EARTH_METAL),
        e(39, "Y", 3, TRANSITION_METAL),
        e(40, "Zr", 4, TRANSITION_METAL),
        e(41, "Nb", 5, TRANSITION_METAL),
        e(42, "Mo", 6, TRANSITION_METAL),
        e(43, "Tc", 7, TRANSITION_METAL),
        e(44, "Ru", 8, TRANSITION_METAL),
        e(45, "Rh", 9, TRANSITION_METAL),
        e(46, "Pd", 10, TRANSITION_METAL),
        e(47, "Ag", 11, TRANSITION_METAL),
        e(48, "Cd", 12, TRANSITION_METAL),
        e(49, "In", 13, POST_TRANSITION_METAL),
        e(50, "Sn", 14, POST_TRANSITION_METAL),
        e(51, "Sb", 15, METALLOID),
        e(52, "Te", 16, METALLOID),
        e(53, "I", 17, HALOGEN),
        e(54, "Xe", 18, NOBLE_GAS),
        e(55, "Cs", 1, ALKALI_METAL),
        e(56, "Ba", 2, ALKALINE_EARTH_METAL),
        e(57, "La", null, LANTHANIDE),
        e(58, "Ce", null, LANTHANIDE),
        e(59, "Pr", null, LANTHANIDE),
        e(60, "Nd", null, LANTHANIDE),
        e(61, "Pm", null, LANTHANIDE),
        e(62, "Sm", null, LANTHANIDE),
        e(63, "Eu", null, LANTHANIDE),
        e(64, "Gd", null, LANTHANIDE),
        e(65, "Tb", null, LANTHANIDE),
        e(66, "Dy", null, LANTHANIDE),
        e(67, "Ho", null, LANTHANIDE),
        e(68, "Er", null, LANTHANIDE),
        e(69, "Tm", null, LANTHANIDE),
        e(70, "Yb", null, LANTHANIDE),
        e(71, "Lu", null, LANTHANIDE),
        e(72, "Hf", 4, TRANSITION_METAL),
        e(73, "Ta", 5, TRANSITION_METAL),
        e(74, "W", 6, TRANSITION_METAL),
        e(75, "Re", 7, TRANSITION_METAL),
        e(76, "Os", 8, TRANSITION_METAL),
        e(77, "Ir", 9, TRANSITION_METAL),
        e(78, "Pt", 10, TRANSITION_METAL),
        e(79, "Au", 11, TRANSITION_METAL),
        e(80, "Hg", 12, TRANSITION_METAL),
        e(81, "Tl", 13, POST_TRANSITION_METAL),
        e(82, "Pb", 14, POST_TRANSITION_METAL),
        e(83, "Bi", 15, POST_TRANSITION_METAL),
        e(84, "Po", 16, POST_TRANSITION_METAL),
        e(85, "At", 17, HALOGEN),
        e(86, "Rn", 18, NOBLE_GAS),
        e(87, "Fr", 1, ALKALI_METAL),
        e(88, "Ra", 2, ALKALINE_EARTH_METAL),
        e(89, "Ac", null, ACTINIDE),
        e(90, "Th", null, ACTINIDE),
        e(91, "Pa", null, ACTINIDE),
        e(92, "U", null, ACTINIDE),
        e(93, "Np", null, ACTINIDE),
        e(94, "Pu", null, ACTINIDE),
        e(95, "Am", null, ACTINIDE),
        e(96, "Cm", null, ACTINIDE),
        e(97, "Bk", null, ACTINIDE),
        e(98, "Cf", null, ACTINIDE),
        e(99, "Es", null, ACTINIDE),
        e(100, "Fm", null, ACTINIDE),
        e(101, "Md", null, ACTINIDE),
        e(102, "No", null, ACTINIDE),
        e(103, "Lr", null, ACTINIDE),
        e(104, "Rf", 4, TRANSITION_METAL),
        e(105, "Db", 5, TRANSITION_METAL),
        e(106, "Sg", 6, TRANSITION_METAL),
        e(107, "Bh", 7, TRANSITION_METAL),
        e(108, "Hs", 8, TRANSITION_METAL),
        e(109, "Mt", 9, UNKNOWN),
        e(110, "Ds", 10, UNKNOWN),
        e(111, "Rg", 11, UNKNOWN),
        e(112, "Cn", 12, UNKNOWN),
        e(113, "Nh", 13, UNKNOWN),
        e(114, "Fl", 14, UNKNOWN),
        e(115, "Mc", 15, UNKNOWN),
        e(116, "Lv", 16, UNKNOWN),
        e(117, "Ts", 17, UNKNOWN),
        e(118, "Og", 18, UNKNOWN),
    )

    operator fun get(atomicNumber: Int): Element = elements[atomicNumber - 1]

    private fun e(z: Int, symbol: String, group: Int?, category: ElementCategory) =
        Element(z, symbol, group, category)
}
