package com.jjas.labpomodoro.domain.model

import com.jjas.labpomodoro.domain.model.ElementCategory.ACTINIDE
import com.jjas.labpomodoro.domain.model.ElementCategory.ALKALINE_EARTH_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.ALKALI_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.HALOGEN
import com.jjas.labpomodoro.domain.model.ElementCategory.LANTHANIDE
import com.jjas.labpomodoro.domain.model.ElementCategory.METALLOID
import com.jjas.labpomodoro.domain.model.ElementCategory.NOBLE_GAS
import com.jjas.labpomodoro.domain.model.ElementCategory.NONMETAL
import com.jjas.labpomodoro.domain.model.ElementCategory.POST_TRANSITION_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.TRANSITION_METAL
import com.jjas.labpomodoro.domain.model.ElementCategory.UNKNOWN

/** Los 118 elementos, ordenados por número atómico (índice = número atómico − 1). */
object PeriodicTable {

    const val SIZE = 118

    val elements: List<Element> = listOf(
        e(1, "H", "Hidrógeno", 1, NONMETAL),
        e(2, "He", "Helio", 18, NOBLE_GAS),
        e(3, "Li", "Litio", 1, ALKALI_METAL),
        e(4, "Be", "Berilio", 2, ALKALINE_EARTH_METAL),
        e(5, "B", "Boro", 13, METALLOID),
        e(6, "C", "Carbono", 14, NONMETAL),
        e(7, "N", "Nitrógeno", 15, NONMETAL),
        e(8, "O", "Oxígeno", 16, NONMETAL),
        e(9, "F", "Flúor", 17, HALOGEN),
        e(10, "Ne", "Neón", 18, NOBLE_GAS),
        e(11, "Na", "Sodio", 1, ALKALI_METAL),
        e(12, "Mg", "Magnesio", 2, ALKALINE_EARTH_METAL),
        e(13, "Al", "Aluminio", 13, POST_TRANSITION_METAL),
        e(14, "Si", "Silicio", 14, METALLOID),
        e(15, "P", "Fósforo", 15, NONMETAL),
        e(16, "S", "Azufre", 16, NONMETAL),
        e(17, "Cl", "Cloro", 17, HALOGEN),
        e(18, "Ar", "Argón", 18, NOBLE_GAS),
        e(19, "K", "Potasio", 1, ALKALI_METAL),
        e(20, "Ca", "Calcio", 2, ALKALINE_EARTH_METAL),
        e(21, "Sc", "Escandio", 3, TRANSITION_METAL),
        e(22, "Ti", "Titanio", 4, TRANSITION_METAL),
        e(23, "V", "Vanadio", 5, TRANSITION_METAL),
        e(24, "Cr", "Cromo", 6, TRANSITION_METAL),
        e(25, "Mn", "Manganeso", 7, TRANSITION_METAL),
        e(26, "Fe", "Hierro", 8, TRANSITION_METAL),
        e(27, "Co", "Cobalto", 9, TRANSITION_METAL),
        e(28, "Ni", "Níquel", 10, TRANSITION_METAL),
        e(29, "Cu", "Cobre", 11, TRANSITION_METAL),
        e(30, "Zn", "Zinc", 12, TRANSITION_METAL),
        e(31, "Ga", "Galio", 13, POST_TRANSITION_METAL),
        e(32, "Ge", "Germanio", 14, METALLOID),
        e(33, "As", "Arsénico", 15, METALLOID),
        e(34, "Se", "Selenio", 16, NONMETAL),
        e(35, "Br", "Bromo", 17, HALOGEN),
        e(36, "Kr", "Kriptón", 18, NOBLE_GAS),
        e(37, "Rb", "Rubidio", 1, ALKALI_METAL),
        e(38, "Sr", "Estroncio", 2, ALKALINE_EARTH_METAL),
        e(39, "Y", "Itrio", 3, TRANSITION_METAL),
        e(40, "Zr", "Circonio", 4, TRANSITION_METAL),
        e(41, "Nb", "Niobio", 5, TRANSITION_METAL),
        e(42, "Mo", "Molibdeno", 6, TRANSITION_METAL),
        e(43, "Tc", "Tecnecio", 7, TRANSITION_METAL),
        e(44, "Ru", "Rutenio", 8, TRANSITION_METAL),
        e(45, "Rh", "Rodio", 9, TRANSITION_METAL),
        e(46, "Pd", "Paladio", 10, TRANSITION_METAL),
        e(47, "Ag", "Plata", 11, TRANSITION_METAL),
        e(48, "Cd", "Cadmio", 12, TRANSITION_METAL),
        e(49, "In", "Indio", 13, POST_TRANSITION_METAL),
        e(50, "Sn", "Estaño", 14, POST_TRANSITION_METAL),
        e(51, "Sb", "Antimonio", 15, METALLOID),
        e(52, "Te", "Telurio", 16, METALLOID),
        e(53, "I", "Yodo", 17, HALOGEN),
        e(54, "Xe", "Xenón", 18, NOBLE_GAS),
        e(55, "Cs", "Cesio", 1, ALKALI_METAL),
        e(56, "Ba", "Bario", 2, ALKALINE_EARTH_METAL),
        e(57, "La", "Lantano", null, LANTHANIDE),
        e(58, "Ce", "Cerio", null, LANTHANIDE),
        e(59, "Pr", "Praseodimio", null, LANTHANIDE),
        e(60, "Nd", "Neodimio", null, LANTHANIDE),
        e(61, "Pm", "Prometio", null, LANTHANIDE),
        e(62, "Sm", "Samario", null, LANTHANIDE),
        e(63, "Eu", "Europio", null, LANTHANIDE),
        e(64, "Gd", "Gadolinio", null, LANTHANIDE),
        e(65, "Tb", "Terbio", null, LANTHANIDE),
        e(66, "Dy", "Disprosio", null, LANTHANIDE),
        e(67, "Ho", "Holmio", null, LANTHANIDE),
        e(68, "Er", "Erbio", null, LANTHANIDE),
        e(69, "Tm", "Tulio", null, LANTHANIDE),
        e(70, "Yb", "Iterbio", null, LANTHANIDE),
        e(71, "Lu", "Lutecio", null, LANTHANIDE),
        e(72, "Hf", "Hafnio", 4, TRANSITION_METAL),
        e(73, "Ta", "Tantalio", 5, TRANSITION_METAL),
        e(74, "W", "Wolframio", 6, TRANSITION_METAL),
        e(75, "Re", "Renio", 7, TRANSITION_METAL),
        e(76, "Os", "Osmio", 8, TRANSITION_METAL),
        e(77, "Ir", "Iridio", 9, TRANSITION_METAL),
        e(78, "Pt", "Platino", 10, TRANSITION_METAL),
        e(79, "Au", "Oro", 11, TRANSITION_METAL),
        e(80, "Hg", "Mercurio", 12, TRANSITION_METAL),
        e(81, "Tl", "Talio", 13, POST_TRANSITION_METAL),
        e(82, "Pb", "Plomo", 14, POST_TRANSITION_METAL),
        e(83, "Bi", "Bismuto", 15, POST_TRANSITION_METAL),
        e(84, "Po", "Polonio", 16, POST_TRANSITION_METAL),
        e(85, "At", "Astato", 17, HALOGEN),
        e(86, "Rn", "Radón", 18, NOBLE_GAS),
        e(87, "Fr", "Francio", 1, ALKALI_METAL),
        e(88, "Ra", "Radio", 2, ALKALINE_EARTH_METAL),
        e(89, "Ac", "Actinio", null, ACTINIDE),
        e(90, "Th", "Torio", null, ACTINIDE),
        e(91, "Pa", "Protactinio", null, ACTINIDE),
        e(92, "U", "Uranio", null, ACTINIDE),
        e(93, "Np", "Neptunio", null, ACTINIDE),
        e(94, "Pu", "Plutonio", null, ACTINIDE),
        e(95, "Am", "Americio", null, ACTINIDE),
        e(96, "Cm", "Curio", null, ACTINIDE),
        e(97, "Bk", "Berkelio", null, ACTINIDE),
        e(98, "Cf", "Californio", null, ACTINIDE),
        e(99, "Es", "Einstenio", null, ACTINIDE),
        e(100, "Fm", "Fermio", null, ACTINIDE),
        e(101, "Md", "Mendelevio", null, ACTINIDE),
        e(102, "No", "Nobelio", null, ACTINIDE),
        e(103, "Lr", "Lawrencio", null, ACTINIDE),
        e(104, "Rf", "Rutherfordio", 4, TRANSITION_METAL),
        e(105, "Db", "Dubnio", 5, TRANSITION_METAL),
        e(106, "Sg", "Seaborgio", 6, TRANSITION_METAL),
        e(107, "Bh", "Bohrio", 7, TRANSITION_METAL),
        e(108, "Hs", "Hasio", 8, TRANSITION_METAL),
        e(109, "Mt", "Meitnerio", 9, UNKNOWN),
        e(110, "Ds", "Darmstatio", 10, UNKNOWN),
        e(111, "Rg", "Roentgenio", 11, UNKNOWN),
        e(112, "Cn", "Copernicio", 12, UNKNOWN),
        e(113, "Nh", "Nihonio", 13, UNKNOWN),
        e(114, "Fl", "Flerovio", 14, UNKNOWN),
        e(115, "Mc", "Moscovio", 15, UNKNOWN),
        e(116, "Lv", "Livermorio", 16, UNKNOWN),
        e(117, "Ts", "Teneso", 17, UNKNOWN),
        e(118, "Og", "Oganesón", 18, UNKNOWN),
    )

    operator fun get(atomicNumber: Int): Element = elements[atomicNumber - 1]

    private fun e(z: Int, symbol: String, name: String, group: Int?, category: ElementCategory) =
        Element(z, symbol, name, group, category)
}
